apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: k8s-sample
data:
  API_INTERNAL_URL: http://api:3001/api
  CLIENT_URL: http://localhost
  DB_DATABASE: articles_db
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_SYNCHRONIZE: "true"
  NEXT_PUBLIC_API_URL: /api
