apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-sample
  namespace: k8s-sample
  labels:
    app.kubernetes.io/part-of: k8s-sample
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: http
