apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: k8s-sample
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_USER: articles_user
  MYSQL_PASSWORD: articles_password